# Generated by Django 3.0.2 on 2024-04-01 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAgriculteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('espace_travail', models.FloatField()),
                ('nombre_employes', models.IntegerField()),
                ('qualite_sol', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produits', models.CharField(max_length=255)),
                ('periode_travail', models.CharField(max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesCapteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('humidite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_data.ProfilAgriculteur')),
            ],
        ),
    ]
