# Generated by Django 4.2.8 on 2024-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_data', '0002_alter_donneescapteur_id_alter_profilagriculteur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilagriculteur',
            name='espace_travail',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='DonneesCapteur',
        ),
    ]
