# Generated by Django 4.2.8 on 2024-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_data', '0003_alter_profilagriculteur_espace_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilagriculteur',
            name='nombre_employes',
            field=models.IntegerField(null=True),
        ),
    ]
