# Generated by Django 4.2.8 on 2024-04-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri_data', '0005_alter_profilagriculteur_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPrixRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prix_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RendementRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rendement', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profilagriculteur',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Budget en euros', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilagriculteur',
            name='espace_travail',
            field=models.FloatField(default=None, help_text='Espace de travail en hectares', null=True),
        ),
        migrations.AlterField(
            model_name='profilagriculteur',
            name='nombre_employes',
            field=models.IntegerField(default=0, help_text="Nombre d'employés", null=True),
        ),
        migrations.AlterField(
            model_name='profilagriculteur',
            name='periode_travail',
            field=models.CharField(help_text="Période de travail principale, ex : 'Janvier - Mars'", max_length=100),
        ),
        migrations.AlterField(
            model_name='profilagriculteur',
            name='produits',
            field=models.CharField(help_text='Liste des produits séparés par des virgules', max_length=255),
        ),
        migrations.CreateModel(
            name='DonneesCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('humidite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_data.profilagriculteur')),
            ],
        ),
    ]
